### ISSUE TITLE
API crashes and burns when Ethereum node is unreachable

### ISSUE THREAD

**Issue by tparvu** [autonomoussoftware/metronome-api#26]
There are a couple of crashes in the attached log file. Search for this string `at hasBinary (/home/metro/metronome-api/node_modules/has-binary2/index.js:56:59)` you will find thousands of these before it crashes.

[metro.log.gz](https://github.com/MetronomeToken/metronome-api/files/1795139/metro.log.gz)

**Comment by ianaya89** [comment]
Solved
